version: '3.8'

services:
  php-app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: php_app
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: teste
    volumes:
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "4500:4500"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge